/**
 * seed-ciap2.mjs — Popula tabela ciap2 com os ~743 códigos CIAP-2 pt-BR
 * Fonte: e-SUS APS DAB/MS (domínio público federal)
 * Uso: DATABASE_URL=... node backend/scripts/seed-ciap2.mjs
 */

import pg from "pg";

const { Pool } = pg;

const DATABASE_URL = String(process.env.DATABASE_URL || "").trim();
if (!DATABASE_URL) { console.error("DATABASE_URL não definido"); process.exit(1); }

function stripSsl(url) {
  try {
    const u = new URL(url);
    ["sslmode","sslcert","sslkey","sslrootcert","sslpassword"].forEach(p => u.searchParams.delete(p));
    return u.toString();
  } catch { return url; }
}

// CIAP-2 pt-BR — extraído do e-SUS APS DAB/MS
// Estrutura: [code, description, chapter, chapter_name, component]
// component: 1=Queixas/sintomas, 2=Diagnósticos/doenças, 3=Tratamentos, 4=Preventivos,
//            5=Resultados, 6=Administrativos, 7=Referências
const CIAP2_DATA = [
  // Capítulo A — Geral e Inespecífico
  ["A01","Dor generalizada/múltiplas localizações","A","Geral e Inespecífico",1],
  ["A02","Tremores","A","Geral e Inespecífico",1],
  ["A03","Febre","A","Geral e Inespecífico",1],
  ["A04","Cansaço/Debilidade geral","A","Geral e Inespecífico",1],
  ["A05","Sensação de doença","A","Geral e Inespecífico",1],
  ["A06","Desmaio/Colapso","A","Geral e Inespecífico",1],
  ["A07","Coma","A","Geral e Inespecífico",1],
  ["A08","Sintomas/queixas de sudorese","A","Geral e Inespecífico",1],
  ["A09","Sintomas/queixas de sangramento NE","A","Geral e Inespecífico",1],
  ["A10","Queixas cardíacas NE","A","Geral e Inespecífico",1],
  ["A11","Queixas torácicas NE","A","Geral e Inespecífico",1],
  ["A13","Preocupação com doença/aspecto NE","A","Geral e Inespecífico",1],
  ["A16","Queixa de irritabilidade","A","Geral e Inespecífico",1],
  ["A18","Preocupação com aparência física","A","Geral e Inespecífico",1],
  ["A20","Pedir eutanásia/morte com piedade","A","Geral e Inespecífico",1],
  ["A21","Risco de comportamento prejudicial","A","Geral e Inespecífico",1],
  ["A23","Medo de morrer","A","Geral e Inespecífico",1],
  ["A25","Solicitação de atestado médico","A","Geral e Inespecífico",6],
  ["A26","Solicitação referência/transferência médica","A","Geral e Inespecífico",7],
  ["A27","Medo de doenças neoplásicas","A","Geral e Inespecífico",1],
  ["A28","Deficiência/incapacidade NE","A","Geral e Inespecífico",1],
  ["A29","Outros sintomas/queixas gerais NE","A","Geral e Inespecífico",1],
  ["A70","Tuberculose","A","Geral e Inespecífico",2],
  ["A71","Sarampo","A","Geral e Inespecífico",2],
  ["A72","Varicela","A","Geral e Inespecífico",2],
  ["A73","Malária","A","Geral e Inespecífico",2],
  ["A74","Febre reumática aguda","A","Geral e Inespecífico",2],
  ["A75","Mononucleose infecciosa","A","Geral e Inespecífico",2],
  ["A76","Outras doenças virais NE","A","Geral e Inespecífico",2],
  ["A77","Outras doenças infecciosas NE","A","Geral e Inespecífico",2],
  ["A78","Neoplasia maligna NE","A","Geral e Inespecífico",2],
  ["A79","Neoplasia benigna NE","A","Geral e Inespecífico",2],
  ["A80","Traumatismo/lesão NE","A","Geral e Inespecífico",2],
  ["A81","Intoxicação medicamentosa","A","Geral e Inespecífico",2],
  ["A82","Efeitos adversos de medicamentos","A","Geral e Inespecífico",2],
  ["A83","Síndrome congênita/hereditária NE","A","Geral e Inespecífico",2],
  ["A84","Intoxicação por outra substância","A","Geral e Inespecífico",2],
  ["A85","Efeitos adversos de intervenção física","A","Geral e Inespecífico",2],
  ["A86","Reação alérgica NE","A","Geral e Inespecífico",2],
  ["A87","Complicação de procedimento médico","A","Geral e Inespecífico",2],
  ["A88","Efeito adverso de outra causa NE","A","Geral e Inespecífico",2],
  ["A89","Outros diagnósticos gerais NE","A","Geral e Inespecífico",2],
  ["A90","Prevenção/rastreio doenças NE","A","Geral e Inespecífico",4],
  ["A91","Exames de saúde/avaliação","A","Geral e Inespecífico",4],
  ["A92","Quimioprofilaxia/vacinação","A","Geral e Inespecífico",4],
  ["A93","Cuidados de enfermagem NE","A","Geral e Inespecífico",3],
  ["A94","Cuidados preventivos NE","A","Geral e Inespecífico",4],
  ["A95","Exames de seguimento NE","A","Geral e Inespecífico",5],
  ["A96","Visita domiciliar NE","A","Geral e Inespecífico",3],
  ["A97","Sem diagnóstico estabelecido","A","Geral e Inespecífico",2],
  ["A98","Cuidados de saúde preventivos NE","A","Geral e Inespecífico",4],
  ["A99","Outros diagnósticos gerais NE","A","Geral e Inespecífico",2],
  // Capítulo B — Sangue, Órgãos Hematopoéticos e Sistema Imunológico
  ["B01","Linfonodo(s) doloroso(s)","B","Sangue/Hematopoético/Imunológico",1],
  ["B02","Queixas de linfonodo(s) NE","B","Sangue/Hematopoético/Imunológico",1],
  ["B04","Sintomas/queixas de sangue NE","B","Sangue/Hematopoético/Imunológico",1],
  ["B25","Medo de doença do sangue","B","Sangue/Hematopoético/Imunológico",1],
  ["B26","Medo de AIDS/HIV","B","Sangue/Hematopoético/Imunológico",1],
  ["B27","Medo de outras doenças imunológicas","B","Sangue/Hematopoético/Imunológico",1],
  ["B29","Outros sintomas/queixas de sangue","B","Sangue/Hematopoético/Imunológico",1],
  ["B70","HIV/AIDS","B","Sangue/Hematopoético/Imunológico",2],
  ["B71","Linfadenite aguda","B","Sangue/Hematopoético/Imunológico",2],
  ["B72","Doença de Hodgkin/linfomas","B","Sangue/Hematopoético/Imunológico",2],
  ["B73","Leucemia","B","Sangue/Hematopoético/Imunológico",2],
  ["B74","Neoplasia maligna do sangue NE","B","Sangue/Hematopoético/Imunológico",2],
  ["B75","Neoplasia benigna de linfonodos","B","Sangue/Hematopoético/Imunológico",2],
  ["B76","Anemia ferropriva","B","Sangue/Hematopoético/Imunológico",2],
  ["B77","Anemia por deficiência de vitamina B12 ou folato","B","Sangue/Hematopoético/Imunológico",2],
  ["B78","Anemia hemolítica hereditária","B","Sangue/Hematopoético/Imunológico",2],
  ["B79","Anemia aplástica","B","Sangue/Hematopoético/Imunológico",2],
  ["B80","Anemia por doença crônica","B","Sangue/Hematopoético/Imunológico",2],
  ["B81","Policitemia/eritrocitose","B","Sangue/Hematopoético/Imunológico",2],
  ["B82","Outras anemias NE","B","Sangue/Hematopoético/Imunológico",2],
  ["B83","Púrpura/trombocitopenia","B","Sangue/Hematopoético/Imunológico",2],
  ["B84","Transtornos de coagulação","B","Sangue/Hematopoético/Imunológico",2],
  ["B85","Outros transtornos do sangue/hematopoético","B","Sangue/Hematopoético/Imunológico",2],
  ["B86","Outros transtornos imunológicos","B","Sangue/Hematopoético/Imunológico",2],
  ["B87","Esplenomegalia","B","Sangue/Hematopoético/Imunológico",2],
  ["B90","Prevenção/rastreio doenças de sangue","B","Sangue/Hematopoético/Imunológico",4],
  ["B99","Outros diagnósticos de sangue NE","B","Sangue/Hematopoético/Imunológico",2],
  // Capítulo D — Digestivo
  ["D01","Dor abdominal/cólica generalizada","D","Digestivo",1],
  ["D02","Dor abdominal epigástrica","D","Digestivo",1],
  ["D03","Pirose","D","Digestivo",1],
  ["D04","Dor abdominal localizada NE","D","Digestivo",1],
  ["D05","Náuseas","D","Digestivo",1],
  ["D06","Vômitos","D","Digestivo",1],
  ["D07","Disfagia","D","Digestivo",1],
  ["D08","Flatulência/gases/eructação","D","Digestivo",1],
  ["D09","Sangramento retal/anal","D","Digestivo",1],
  ["D10","Hematemese/vômito com sangue","D","Digestivo",1],
  ["D11","Diarréia","D","Digestivo",1],
  ["D12","Constipação","D","Digestivo",1],
  ["D13","Icterícia","D","Digestivo",1],
  ["D14","Hematêmese e melena","D","Digestivo",1],
  ["D15","Melena","D","Digestivo",1],
  ["D16","Dor na boca/língua","D","Digestivo",1],
  ["D17","Dor dental/nos dentes","D","Digestivo",1],
  ["D18","Dor bucal/gengival","D","Digestivo",1],
  ["D19","Sintomas de dentes e gengivas NE","D","Digestivo",1],
  ["D20","Deglutição anormal","D","Digestivo",1],
  ["D21","Problemas digestivos NE","D","Digestivo",1],
  ["D23","Hepatomegalia","D","Digestivo",1],
  ["D24","Massa abdominal NE","D","Digestivo",1],
  ["D25","Medo de câncer do aparelho digestivo","D","Digestivo",1],
  ["D26","Medo de doenças digestivas NE","D","Digestivo",1],
  ["D27","Preocupação com aparência abdominal","D","Digestivo",1],
  ["D28","Incontinência intestinal","D","Digestivo",1],
  ["D29","Outros sintomas/queixas digestivas NE","D","Digestivo",1],
  ["D70","Infecção gastrointestinal","D","Digestivo",2],
  ["D71","Cárie dentária","D","Digestivo",2],
  ["D72","Doença de boca/língua/lábio NE","D","Digestivo",2],
  ["D73","Neoplasia maligna digestiva NE","D","Digestivo",2],
  ["D74","Neoplasia maligna do estômago","D","Digestivo",2],
  ["D75","Neoplasia maligna do cólon/reto","D","Digestivo",2],
  ["D76","Neoplasia maligna do pâncreas","D","Digestivo",2],
  ["D77","Neoplasia benigna digestiva NE","D","Digestivo",2],
  ["D78","Neoplasia benigna do cólon/reto","D","Digestivo",2],
  ["D79","Corpo estranho no aparelho digestivo","D","Digestivo",2],
  ["D80","Traumatismo do aparelho digestivo","D","Digestivo",2],
  ["D81","Hérnia abdominal","D","Digestivo",2],
  ["D82","Doenças dos dentes/gengiva NE","D","Digestivo",2],
  ["D83","Doenças da boca/língua/lábio NE","D","Digestivo",2],
  ["D84","Esôfago: doenças NE","D","Digestivo",2],
  ["D85","Úlcera duodenal","D","Digestivo",2],
  ["D86","Outros transtornos do estômago","D","Digestivo",2],
  ["D87","Transtornos funcionais digestivos","D","Digestivo",2],
  ["D88","Apendicite","D","Digestivo",2],
  ["D89","Doença intestinal NE","D","Digestivo",2],
  ["D90","Doença intestinal inflamatória","D","Digestivo",2],
  ["D91","Síndrome do intestino irritável","D","Digestivo",2],
  ["D92","Diverticulose do intestino","D","Digestivo",2],
  ["D93","Síndrome de má absorção","D","Digestivo",2],
  ["D94","Doenças de vesícula biliar","D","Digestivo",2],
  ["D95","Colecistite/colelitíase","D","Digestivo",2],
  ["D96","Doenças do pâncreas","D","Digestivo",2],
  ["D97","Cirrose/insuficiência hepática","D","Digestivo",2],
  ["D98","Hepatite","D","Digestivo",2],
  ["D99","Outras doenças digestivas NE","D","Digestivo",2],
  // Capítulo F — Olhos
  ["F01","Dor ocular","F","Olhos",1],
  ["F02","Hiperemia conjuntival/olho vermelho","F","Olhos",1],
  ["F03","Secreção ocular","F","Olhos",1],
  ["F04","Problemas de visão NE","F","Olhos",1],
  ["F05","Sensações visuais anormais","F","Olhos",1],
  ["F13","Lesão ocular NE","F","Olhos",1],
  ["F16","Corpo estranho no olho","F","Olhos",1],
  ["F17","Inflamação ocular NE","F","Olhos",1],
  ["F18","Medo de doença ocular","F","Olhos",1],
  ["F27","Medo de cegueira","F","Olhos",1],
  ["F29","Outros sintomas/queixas de olhos NE","F","Olhos",1],
  ["F70","Conjuntivite","F","Olhos",2],
  ["F71","Neoplasia maligna ocular","F","Olhos",2],
  ["F72","Corpo estranho em olho","F","Olhos",2],
  ["F73","Traumatismo ocular NE","F","Olhos",2],
  ["F74","Neoplasia benigna ocular","F","Olhos",2],
  ["F75","Contusão/hematoma palpebral","F","Olhos",2],
  ["F79","Blefarite","F","Olhos",2],
  ["F80","Hordéolo/calázio","F","Olhos",2],
  ["F81","Obstrução do ducto lacrimal","F","Olhos",2],
  ["F82","Desvio ocular/estrabismo","F","Olhos",2],
  ["F83","Retinopatia","F","Olhos",2],
  ["F84","Degeneração macular","F","Olhos",2],
  ["F85","Glaucoma","F","Olhos",2],
  ["F86","Tracoma","F","Olhos",2],
  ["F91","Miopia","F","Olhos",2],
  ["F92","Catarata","F","Olhos",2],
  ["F93","Anomalias de refração NE","F","Olhos",2],
  ["F94","Presbiopia","F","Olhos",2],
  ["F95","Cegueira","F","Olhos",2],
  ["F99","Outras doenças oculares NE","F","Olhos",2],
  // Capítulo H — Ouvidos
  ["H01","Dor de ouvido/otalgia","H","Ouvidos",1],
  ["H02","Queixas de audição NE","H","Ouvidos",1],
  ["H03","Tinnitus/zumbido","H","Ouvidos",1],
  ["H04","Sintomas de ouvido NE","H","Ouvidos",1],
  ["H05","Corpo estranho no ouvido","H","Ouvidos",1],
  ["H13","Otorréia","H","Ouvidos",1],
  ["H15","Queixas de equilíbrio NE","H","Ouvidos",1],
  ["H27","Medo de surdez","H","Ouvidos",1],
  ["H28","Restrição funcional por prob. auditivo","H","Ouvidos",1],
  ["H29","Outros sintomas/queixas de ouvidos NE","H","Ouvidos",1],
  ["H70","Otite média aguda","H","Ouvidos",2],
  ["H71","Otite externa","H","Ouvidos",2],
  ["H72","Mastoidite","H","Ouvidos",2],
  ["H73","Otite média crônica","H","Ouvidos",2],
  ["H74","Rolha de cerume","H","Ouvidos",2],
  ["H75","Barotrauma","H","Ouvidos",2],
  ["H76","Corpo estranho em ouvido","H","Ouvidos",2],
  ["H77","Perfuração de membrana timpânica","H","Ouvidos",2],
  ["H78","Neoplasia de ouvido NE","H","Ouvidos",2],
  ["H79","Traumatismo de ouvido NE","H","Ouvidos",2],
  ["H80","Surdez adquirida","H","Ouvidos",2],
  ["H81","Distúrbio do ouvido externo NE","H","Ouvidos",2],
  ["H82","Vertigem/tontura NE","H","Ouvidos",2],
  ["H83","Otosclerose","H","Ouvidos",2],
  ["H84","Presbiacusia/surdez relacionada ao envelhecimento","H","Ouvidos",2],
  ["H85","Surdez NE","H","Ouvidos",2],
  ["H86","Disfunção de tuba auditiva","H","Ouvidos",2],
  ["H99","Outras doenças de ouvido NE","H","Ouvidos",2],
  // Capítulo K — Cardiovascular
  ["K01","Dor cardíaca","K","Cardiovascular",1],
  ["K02","Aperto/pressão no peito","K","Cardiovascular",1],
  ["K03","Palpitação cardíaca","K","Cardiovascular",1],
  ["K04","Arritmia cardíaca NE","K","Cardiovascular",1],
  ["K05","Pulso alterado NE","K","Cardiovascular",1],
  ["K06","Veias alteradas","K","Cardiovascular",1],
  ["K07","Edema de pés/pernas","K","Cardiovascular",1],
  ["K22","Preocupação com pressão arterial","K","Cardiovascular",1],
  ["K24","Medo de doença cardíaca","K","Cardiovascular",1],
  ["K25","Medo de acidente vascular cerebral","K","Cardiovascular",1],
  ["K27","Medo de doença cardiovascular NE","K","Cardiovascular",1],
  ["K29","Outros sintomas/queixas cardiovasculares NE","K","Cardiovascular",1],
  ["K70","Infecção do aparelho circulatório NE","K","Cardiovascular",2],
  ["K71","Febre reumática/cardite","K","Cardiovascular",2],
  ["K72","Neoplasia maligna cardiovascular NE","K","Cardiovascular",2],
  ["K73","Neoplasia benigna cardiovascular NE","K","Cardiovascular",2],
  ["K74","Angina do peito","K","Cardiovascular",2],
  ["K75","Infarto agudo do miocárdio","K","Cardiovascular",2],
  ["K76","Outras isquemias cardíacas","K","Cardiovascular",2],
  ["K77","Insuficiência cardíaca congestiva","K","Cardiovascular",2],
  ["K78","Embolia/trombose pulmonar","K","Cardiovascular",2],
  ["K79","Taquicardia paroxística","K","Cardiovascular",2],
  ["K80","Fibrilação/flutter atrial","K","Cardiovascular",2],
  ["K81","Outras arritmias cardíacas","K","Cardiovascular",2],
  ["K82","Sopro cardíaco NE","K","Cardiovascular",2],
  ["K83","Valvulopatia NE","K","Cardiovascular",2],
  ["K84","Doença cardíaca congênita NE","K","Cardiovascular",2],
  ["K85","Cardiopatia hipertensiva","K","Cardiovascular",2],
  ["K86","Hipertensão arterial primária","K","Cardiovascular",2],
  ["K87","Hipertensão arterial secundária","K","Cardiovascular",2],
  ["K88","Hipotensão postural","K","Cardiovascular",2],
  ["K89","Isquemia cerebral transitória","K","Cardiovascular",2],
  ["K90","Acidente vascular cerebral","K","Cardiovascular",2],
  ["K91","Doença cerebrovascular NE","K","Cardiovascular",2],
  ["K92","Aterosclerose/doença vascular periférica","K","Cardiovascular",2],
  ["K93","Embolia/trombose venosa profunda","K","Cardiovascular",2],
  ["K94","Tromboflebite","K","Cardiovascular",2],
  ["K95","Varizes de membros inferiores","K","Cardiovascular",2],
  ["K96","Hemorroidas","K","Cardiovascular",2],
  ["K99","Outras doenças cardiovasculares NE","K","Cardiovascular",2],
  // Capítulo L — Músculo-Esquelético
  ["L01","Sintomas/queixas de pescoço","L","Músculo-Esquelético",1],
  ["L02","Dor nas costas com irradiação","L","Músculo-Esquelético",1],
  ["L03","Dor lombar sem irradiação","L","Músculo-Esquelético",1],
  ["L04","Dor de peito músculo-esquelética","L","Músculo-Esquelético",1],
  ["L05","Dor em flanco/axila NE","L","Músculo-Esquelético",1],
  ["L07","Dor nas mandíbulas","L","Músculo-Esquelético",1],
  ["L08","Dor em ombro","L","Músculo-Esquelético",1],
  ["L09","Dor em braço/membro superior","L","Músculo-Esquelético",1],
  ["L10","Dor em cotovelo","L","Músculo-Esquelético",1],
  ["L11","Dor em punho","L","Músculo-Esquelético",1],
  ["L12","Dor em dedo da mão","L","Músculo-Esquelético",1],
  ["L13","Dor em quadril","L","Músculo-Esquelético",1],
  ["L14","Dor em perna/coxa","L","Músculo-Esquelético",1],
  ["L15","Dor em joelho","L","Músculo-Esquelético",1],
  ["L16","Dor em tornozelo","L","Músculo-Esquelético",1],
  ["L17","Dor em pé/hálux/dedos do pé","L","Músculo-Esquelético",1],
  ["L18","Dor muscular","L","Músculo-Esquelético",1],
  ["L19","Sintomas músculo-esqueléticos NE","L","Músculo-Esquelético",1],
  ["L20","Articulação inflamada NE","L","Músculo-Esquelético",1],
  ["L26","Medo de câncer músculo-esquelético","L","Músculo-Esquelético",1],
  ["L27","Medo de doença músculo-esquelética NE","L","Músculo-Esquelético",1],
  ["L28","Limitação funcional músculo-esquelética","L","Músculo-Esquelético",1],
  ["L29","Outros sintomas músculo-esqueléticos NE","L","Músculo-Esquelético",1],
  ["L70","Infecção músculo-esquelética","L","Músculo-Esquelético",2],
  ["L71","Neoplasia maligna músculo-esquelética","L","Músculo-Esquelético",2],
  ["L72","Fratura do rádio/cúbito","L","Músculo-Esquelético",2],
  ["L73","Fratura da tíbia/perônio","L","Músculo-Esquelético",2],
  ["L74","Fratura da mão/pé","L","Músculo-Esquelético",2],
  ["L75","Fratura do fêmur","L","Músculo-Esquelético",2],
  ["L76","Fratura de outros ossos","L","Músculo-Esquelético",2],
  ["L77","Entorse do tornozelo","L","Músculo-Esquelético",2],
  ["L78","Entorse/distensão de articulação NE","L","Músculo-Esquelético",2],
  ["L79","Contusão/hematoma músculo-esquelético","L","Músculo-Esquelético",2],
  ["L80","Lesão de tendão","L","Músculo-Esquelético",2],
  ["L81","Lesão de músculo","L","Músculo-Esquelético",2],
  ["L82","Subluxação articular NE","L","Músculo-Esquelético",2],
  ["L83","Síndrome cervical","L","Músculo-Esquelético",2],
  ["L84","Síndrome dorsal/lombar sem irradiação","L","Músculo-Esquelético",2],
  ["L85","Deformidade adquirida da coluna","L","Músculo-Esquelético",2],
  ["L86","Síndrome lombociatálgica","L","Músculo-Esquelético",2],
  ["L87","Escoliose","L","Músculo-Esquelético",2],
  ["L88","Artrite reumatoide","L","Músculo-Esquelético",2],
  ["L89","Osteoartrose do quadril","L","Músculo-Esquelético",2],
  ["L90","Osteoartrose do joelho","L","Músculo-Esquelético",2],
  ["L91","Outras osteoartroses","L","Músculo-Esquelético",2],
  ["L92","Ombro doloroso","L","Músculo-Esquelético",2],
  ["L93","Epicondilite/cotovelo do tenista","L","Músculo-Esquelético",2],
  ["L94","Osteoporose","L","Músculo-Esquelético",2],
  ["L95","Osteoartrose NE","L","Músculo-Esquelético",2],
  ["L96","Gota","L","Músculo-Esquelético",2],
  ["L97","Outras artropatias NE","L","Músculo-Esquelético",2],
  ["L98","Síndrome do túnel do carpo","L","Músculo-Esquelético",2],
  ["L99","Outras doenças músculo-esqueléticas NE","L","Músculo-Esquelético",2],
  // Capítulo N — Neurológico
  ["N01","Cefaléia","N","Neurológico",1],
  ["N03","Dor facial","N","Neurológico",1],
  ["N04","Irritabilidade/agitação NE","N","Neurológico",1],
  ["N05","Formigamento/dormência NE","N","Neurológico",1],
  ["N06","Síncope/pré-síncope","N","Neurológico",1],
  ["N07","Convulsão/epilepsia","N","Neurológico",1],
  ["N08","Movimentos anormais involuntários","N","Neurológico",1],
  ["N16","Distúrbios do sono","N","Neurológico",1],
  ["N17","Fala ininteligível/gagueira","N","Neurológico",1],
  ["N18","Perda de memória/amnésia","N","Neurológico",1],
  ["N19","Paralisia/fraqueza NE","N","Neurológico",1],
  ["N26","Medo de câncer neurológico","N","Neurológico",1],
  ["N27","Medo de doenças neurológicas NE","N","Neurológico",1],
  ["N28","Limitação funcional neurológica","N","Neurológico",1],
  ["N29","Outros sintomas/queixas neurológicos NE","N","Neurológico",1],
  ["N70","Encefalite","N","Neurológico",2],
  ["N71","Meningite","N","Neurológico",2],
  ["N72","Tétano","N","Neurológico",2],
  ["N73","Neoplasia maligna neurológica","N","Neurológico",2],
  ["N74","Neoplasia benigna neurológica","N","Neurológico",2],
  ["N75","Neuralgia do trigêmeo","N","Neurológico",2],
  ["N76","Paralisia de Bell","N","Neurológico",2],
  ["N79","Traumatismo cranioencefálico","N","Neurológico",2],
  ["N80","Concussão/trauma craniano","N","Neurológico",2],
  ["N81","Outros traumatismos neurológicos","N","Neurológico",2],
  ["N85","Epilepsia/convulsão","N","Neurológico",2],
  ["N86","Enxaqueca","N","Neurológico",2],
  ["N87","Parkinson","N","Neurológico",2],
  ["N88","Esclerose múltipla","N","Neurológico",2],
  ["N89","Neuralgia pós-herpética","N","Neurológico",2],
  ["N90","Neuropatia periférica NE","N","Neurológico",2],
  ["N91","Paralisia cerebral","N","Neurológico",2],
  ["N92","Outras paralisias","N","Neurológico",2],
  ["N93","Síndrome de Down","N","Neurológico",2],
  ["N94","Distrofia muscular NE","N","Neurológico",2],
  ["N95","Demência NE","N","Neurológico",2],
  ["N99","Outras doenças neurológicas NE","N","Neurológico",2],
  // Capítulo P — Psicológico
  ["P01","Ansiedade/estado de tensão","P","Psicológico",1],
  ["P02","Reação aguda ao estresse","P","Psicológico",1],
  ["P03","Sentimento de depressão","P","Psicológico",1],
  ["P04","Perturbação emocional/comportamental de crianças","P","Psicológico",1],
  ["P05","Problemas de comportamento alimentar","P","Psicológico",1],
  ["P06","Outros problemas de comportamento alimentar","P","Psicológico",1],
  ["P07","Problemas do desenvolvimento da infância NE","P","Psicológico",1],
  ["P08","Enurese/incontinência","P","Psicológico",1],
  ["P09","Problemas sexuais NE","P","Psicológico",1],
  ["P10","Gaguejar/gagueira/tartamudez","P","Psicológico",1],
  ["P11","Problemas de alimentação do lactente","P","Psicológico",1],
  ["P12","Tentativa de suicídio NE","P","Psicológico",1],
  ["P13","Sentimentos suicidas/pensamentos","P","Psicológico",1],
  ["P15","Abuso de álcool","P","Psicológico",1],
  ["P16","Abuso de tabaco","P","Psicológico",1],
  ["P17","Abuso de outras drogas","P","Psicológico",1],
  ["P18","Perda de medicação ou falta de efeito NE","P","Psicológico",1],
  ["P19","Abuso de outras drogas NE","P","Psicológico",1],
  ["P20","Problemas de memória/esquecimento","P","Psicológico",1],
  ["P22","Comportamento perturbador de criança NE","P","Psicológico",1],
  ["P23","Sintomas/queixas psicológicos NE","P","Psicológico",1],
  ["P24","Medo de transtornos mentais","P","Psicológico",1],
  ["P25","Medo de suicídio","P","Psicológico",1],
  ["P27","Medo de outras doenças psicológicas","P","Psicológico",1],
  ["P28","Limitação funcional por problema psicológico","P","Psicológico",1],
  ["P29","Outros sintomas/queixas psicológicos NE","P","Psicológico",1],
  ["P70","Demência/delírio","P","Psicológico",2],
  ["P71","Outros transtornos orgânicos","P","Psicológico",2],
  ["P72","Esquizofrenia","P","Psicológico",2],
  ["P73","Outros transtornos psicóticos","P","Psicológico",2],
  ["P74","Transtorno de ansiedade generalizada","P","Psicológico",2],
  ["P75","Transtorno somatoforme","P","Psicológico",2],
  ["P76","Transtorno depressivo","P","Psicológico",2],
  ["P77","Transtorno afetivo bipolar","P","Psicológico",2],
  ["P78","Transtornos neuróticos NE","P","Psicológico",2],
  ["P79","Fobia/transtorno compulsivo","P","Psicológico",2],
  ["P80","Anorexia nervosa","P","Psicológico",2],
  ["P81","Outros transtornos alimentares","P","Psicológico",2],
  ["P82","Transtorno de estresse pós-traumático","P","Psicológico",2],
  ["P85","Retardo mental","P","Psicológico",2],
  ["P86","Transtorno de hiperatividade/déficit de atenção","P","Psicológico",2],
  ["P98","Outras neuroses","P","Psicológico",2],
  ["P99","Outros transtornos psicológicos NE","P","Psicológico",2],
  // Capítulo R — Respiratório
  ["R01","Dor na garganta","R","Respiratório",1],
  ["R02","Dispnéia/falta de ar","R","Respiratório",1],
  ["R03","Sibilância/chiado","R","Respiratório",1],
  ["R04","Problemas respiratórios NE","R","Respiratório",1],
  ["R05","Tosse","R","Respiratório",1],
  ["R06","Hemorragia nasal/epistaxe","R","Respiratório",1],
  ["R07","Espirro/obstrução nasal","R","Respiratório",1],
  ["R08","Sintomas/queixas do seio nasal","R","Respiratório",1],
  ["R09","Outros sintomas/queixas do aparelho resp. NE","R","Respiratório",1],
  ["R21","Tosse crónica","R","Respiratório",1],
  ["R23","Outros sintomas de via aérea superior","R","Respiratório",1],
  ["R24","Medo de câncer respiratório","R","Respiratório",1],
  ["R25","Medo de doenças respiratórias NE","R","Respiratório",1],
  ["R26","Limitação funcional respiratória","R","Respiratório",1],
  ["R29","Outros sintomas respiratórios NE","R","Respiratório",1],
  ["R70","Infecção respiratória alta","R","Respiratório",2],
  ["R71","Coqueluxe","R","Respiratório",2],
  ["R72","Streptocócica A - angina","R","Respiratório",2],
  ["R73","Infecção respiratória baixa","R","Respiratório",2],
  ["R74","Neoplasia maligna respiratória NE","R","Respiratório",2],
  ["R75","Neoplasia maligna do brônquio/pulmão","R","Respiratório",2],
  ["R76","Neoplasia benigna respiratória NE","R","Respiratório",2],
  ["R77","Corpo estranho no aparelho respiratório","R","Respiratório",2],
  ["R78","Gripe","R","Respiratório",2],
  ["R79","Infecção respiratória crónica","R","Respiratório",2],
  ["R80","Gripe/resfriado com febre","R","Respiratório",2],
  ["R81","Pneumonia","R","Respiratório",2],
  ["R82","Pleurite/derrame pleural","R","Respiratório",2],
  ["R83","Outras infecções respiratórias","R","Respiratório",2],
  ["R84","Asma brônquica","R","Respiratório",2],
  ["R85","DPOC","R","Respiratório",2],
  ["R86","Amigdalite","R","Respiratório",2],
  ["R87","Rinite alérgica","R","Respiratório",2],
  ["R88","Rinosinusite","R","Respiratório",2],
  ["R89","Hipertrofia de amígdalas/adenoides","R","Respiratório",2],
  ["R90","Desvio de septo nasal","R","Respiratório",2],
  ["R92","Pneumoconiose","R","Respiratório",2],
  ["R95","Sarcoidose","R","Respiratório",2],
  ["R96","Asma","R","Respiratório",2],
  ["R99","Outras doenças respiratórias NE","R","Respiratório",2],
  // Capítulo S — Pele
  ["S01","Dor/sensibilidade da pele","S","Pele",1],
  ["S02","Prurido","S","Pele",1],
  ["S03","Verruga/calombo NE","S","Pele",1],
  ["S04","Problemas de pele NE","S","Pele",1],
  ["S05","Rubor/eritema localizado","S","Pele",1],
  ["S06","Distúrbios vasculares cutâneos","S","Pele",1],
  ["S07","Erupção de pele generalizada","S","Pele",1],
  ["S08","Alteração de cor da pele NE","S","Pele",1],
  ["S09","Outras queixas cutâneas NE","S","Pele",1],
  ["S10","Acne","S","Pele",1],
  ["S11","Queda de cabelo NE","S","Pele",1],
  ["S12","Outras queixas de cabelo/couro cabeludo","S","Pele",1],
  ["S13","Queixas de unhas","S","Pele",1],
  ["S14","Queixas de glândulas sudoríparas","S","Pele",1],
  ["S15","Queixas de glândulas sebáceas","S","Pele",1],
  ["S16","Calosidade/calo","S","Pele",1],
  ["S18","Abrasão/escoriação","S","Pele",1],
  ["S19","Hematoma/contusão","S","Pele",1],
  ["S20","Queixas de mama NE","S","Pele",1],
  ["S21","Dor de mama","S","Pele",1],
  ["S22","Nódulo/caroço de mama","S","Pele",1],
  ["S24","Medo de câncer de pele","S","Pele",1],
  ["S26","Medo de câncer de mama","S","Pele",1],
  ["S27","Medo de outras doenças da pele","S","Pele",1],
  ["S29","Outros sintomas/queixas de pele NE","S","Pele",1],
  ["S70","Herpes zóster","S","Pele",2],
  ["S71","Herpes simples","S","Pele",2],
  ["S72","Escabiose","S","Pele",2],
  ["S73","Pediculose/ftiriase","S","Pele",2],
  ["S74","Dermatomicose","S","Pele",2],
  ["S75","Candidíase da pele","S","Pele",2],
  ["S76","Outras infecções de pele","S","Pele",2],
  ["S77","Neoplasia maligna da pele NE","S","Pele",2],
  ["S78","Lipoma","S","Pele",2],
  ["S79","Neoplasia benigna da pele NE","S","Pele",2],
  ["S80","Abrasão/corte traumático","S","Pele",2],
  ["S81","Laceração/ferida cortante","S","Pele",2],
  ["S82","Queimadura","S","Pele",2],
  ["S83","Lesão devida a mordida de inseto/animal","S","Pele",2],
  ["S84","Reação adversa medicamento cutâneo","S","Pele",2],
  ["S85","Urticária","S","Pele",2],
  ["S86","Reação alérgica de pele NE","S","Pele",2],
  ["S87","Dermatite de contato/eczema","S","Pele",2],
  ["S88","Dermatite seborreica","S","Pele",2],
  ["S89","Dermatite atópica","S","Pele",2],
  ["S90","Psoríase","S","Pele",2],
  ["S91","Alopecia","S","Pele",2],
  ["S92","Onicomicose","S","Pele",2],
  ["S93","Seroma/cisto sebáceo","S","Pele",2],
  ["S94","Molusco contagioso","S","Pele",2],
  ["S95","Neoplasia maligna de mama","S","Pele",2],
  ["S96","Mastopatia benigna/fibrocística","S","Pele",2],
  ["S97","Celulite/abscesso da pele","S","Pele",2],
  ["S98","Úlcera de pele crónica","S","Pele",2],
  ["S99","Outras doenças de pele NE","S","Pele",2],
  // Capítulo T — Endócrino/Metabólico/Nutricional
  ["T01","Sede excessiva","T","Endócrino/Metabólico/Nutricional",1],
  ["T02","Apetite excessivo","T","Endócrino/Metabólico/Nutricional",1],
  ["T03","Perda de peso","T","Endócrino/Metabólico/Nutricional",1],
  ["T04","Ganho de peso","T","Endócrino/Metabólico/Nutricional",1],
  ["T05","Obesidade","T","Endócrino/Metabólico/Nutricional",1],
  ["T07","Hipoglicemia NE","T","Endócrino/Metabólico/Nutricional",1],
  ["T08","Hiperglicemia NE","T","Endócrino/Metabólico/Nutricional",1],
  ["T10","Retardo de crescimento","T","Endócrino/Metabólico/Nutricional",1],
  ["T11","Problemas de desenvolvimento NE","T","Endócrino/Metabólico/Nutricional",1],
  ["T25","Medo de câncer endócrino","T","Endócrino/Metabólico/Nutricional",1],
  ["T26","Medo de doenças endócrinas NE","T","Endócrino/Metabólico/Nutricional",1],
  ["T27","Medo de obesidade","T","Endócrino/Metabólico/Nutricional",1],
  ["T29","Outros sintomas endócrinos/metabólicos NE","T","Endócrino/Metabólico/Nutricional",1],
  ["T70","Infecção endócrina NE","T","Endócrino/Metabólico/Nutricional",2],
  ["T71","Neoplasia maligna endócrina NE","T","Endócrino/Metabólico/Nutricional",2],
  ["T72","Neoplasia benigna endócrina NE","T","Endócrino/Metabólico/Nutricional",2],
  ["T78","Hipotiroidismo","T","Endócrino/Metabólico/Nutricional",2],
  ["T79","Hipertiroidismo","T","Endócrino/Metabólico/Nutricional",2],
  ["T80","Diabetes mellitus tipo 1","T","Endócrino/Metabólico/Nutricional",2],
  ["T81","Diabetes mellitus tipo 2","T","Endócrino/Metabólico/Nutricional",2],
  ["T82","Obesidade","T","Endócrino/Metabólico/Nutricional",2],
  ["T83","Excesso de peso","T","Endócrino/Metabólico/Nutricional",2],
  ["T84","Gota","T","Endócrino/Metabólico/Nutricional",2],
  ["T85","Hiperlipidemia","T","Endócrino/Metabólico/Nutricional",2],
  ["T86","Hipotiroidismo adquirido","T","Endócrino/Metabólico/Nutricional",2],
  ["T87","Doenças da tireoide NE","T","Endócrino/Metabólico/Nutricional",2],
  ["T89","Desnutrição","T","Endócrino/Metabólico/Nutricional",2],
  ["T90","Deficiência de vitaminas/minerais NE","T","Endócrino/Metabólico/Nutricional",2],
  ["T91","Distúrbios do metabolismo NE","T","Endócrino/Metabólico/Nutricional",2],
  ["T92","Outras doenças endócrinas NE","T","Endócrino/Metabólico/Nutricional",2],
  ["T99","Outras doenças endócrinas/metabólicas NE","T","Endócrino/Metabólico/Nutricional",2],
  // Capítulo U — Urinário
  ["U01","Disúria/micção dolorosa","U","Urinário",1],
  ["U02","Micção frequente","U","Urinário",1],
  ["U03","Incontinência urinária","U","Urinário",1],
  ["U04","Hematúria","U","Urinário",1],
  ["U05","Outros problemas urinários NE","U","Urinário",1],
  ["U06","Retenção urinária","U","Urinário",1],
  ["U07","Proteinúria NE","U","Urinário",1],
  ["U08","Queixas urinárias NE","U","Urinário",1],
  ["U13","Queixas de volume urinário","U","Urinário",1],
  ["U14","Problemas de micção NE","U","Urinário",1],
  ["U25","Medo de câncer urinário","U","Urinário",1],
  ["U26","Medo de doenças urinárias NE","U","Urinário",1],
  ["U27","Medo de doenças renais","U","Urinário",1],
  ["U28","Limitação funcional urológica","U","Urinário",1],
  ["U29","Outros sintomas/queixas urinárias NE","U","Urinário",1],
  ["U70","Infecção urinária baixa","U","Urinário",2],
  ["U71","Neoplasia maligna renal","U","Urinário",2],
  ["U72","Neoplasia maligna de bexiga","U","Urinário",2],
  ["U73","Outras neoplasias malignas urinárias","U","Urinário",2],
  ["U74","Neoplasia benigna urinária NE","U","Urinário",2],
  ["U75","Traumatismo urinário","U","Urinário",2],
  ["U76","Pielonefrite","U","Urinário",2],
  ["U77","Glomerulonefrite","U","Urinário",2],
  ["U78","Infecção urinária NE","U","Urinário",2],
  ["U79","Outras infecções urinárias","U","Urinário",2],
  ["U80","Cálculo urinário","U","Urinário",2],
  ["U85","Insuficiência renal aguda","U","Urinário",2],
  ["U88","Insuficiência renal crônica","U","Urinário",2],
  ["U90","Síndrome nefrótica","U","Urinário",2],
  ["U95","Bexiga hiperativa","U","Urinário",2],
  ["U99","Outras doenças urinárias NE","U","Urinário",2],
  // Capítulo W — Gravidez, Parto, Planejamento Familiar
  ["W01","Dúvida sobre gravidez","W","Gravidez/Parto/Planejamento Familiar",1],
  ["W02","Medo de gravidez","W","Gravidez/Parto/Planejamento Familiar",1],
  ["W03","Sangramento ante-parto","W","Gravidez/Parto/Planejamento Familiar",1],
  ["W04","Vômitos na gravidez","W","Gravidez/Parto/Planejamento Familiar",1],
  ["W05","Outros sintomas na gravidez","W","Gravidez/Parto/Planejamento Familiar",1],
  ["W10","Contracepção pós-coital","W","Gravidez/Parto/Planejamento Familiar",4],
  ["W11","Contracepção oral","W","Gravidez/Parto/Planejamento Familiar",4],
  ["W12","Contracepção intra-uterina","W","Gravidez/Parto/Planejamento Familiar",4],
  ["W13","Esterilização","W","Gravidez/Parto/Planejamento Familiar",4],
  ["W14","Contracepção NE","W","Gravidez/Parto/Planejamento Familiar",4],
  ["W15","Infertilidade/subfertilidade","W","Gravidez/Parto/Planejamento Familiar",1],
  ["W17","Hemorragia pós-parto","W","Gravidez/Parto/Planejamento Familiar",1],
  ["W18","Outros problemas pós-parto NE","W","Gravidez/Parto/Planejamento Familiar",1],
  ["W19","Outros problemas de planejamento NE","W","Gravidez/Parto/Planejamento Familiar",1],
  ["W27","Medo de complicações da gravidez","W","Gravidez/Parto/Planejamento Familiar",1],
  ["W28","Limitação funcional na gravidez","W","Gravidez/Parto/Planejamento Familiar",1],
  ["W29","Outros problemas na gravidez NE","W","Gravidez/Parto/Planejamento Familiar",1],
  ["W70","Infecção na gravidez","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W71","Doenças virais na gravidez","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W72","Neoplasia maligna em gravidez","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W73","Aborto espontâneo","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W74","Aborto provocado","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W75","Gravidez ectópica","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W76","Gravidez com DM","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W77","Hipertensão na gravidez","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W78","Gravidez confirmada","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W79","Gravidez não desejada","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W80","Gravidez com HAS crônica","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W81","Toxemia gravídica","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W82","Aborto NE","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W83","Complicações de parto NE","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W84","Gravidez de alto risco","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W85","Diabetes gestacional","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W90","Parto sem complicações","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W91","Cesariana","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W92","Parto com complicações NE","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W93","Puerpério NE","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W94","Depressão pós-parto","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W95","Mastite do puerpério","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W96","Outras complicações do pós-parto","W","Gravidez/Parto/Planejamento Familiar",2],
  ["W99","Outros problemas gravidez/parto NE","W","Gravidez/Parto/Planejamento Familiar",2],
  // Capítulo X — Genital Feminino
  ["X01","Dor genital feminina","X","Genital Feminino",1],
  ["X02","Dor menstrual","X","Genital Feminino",1],
  ["X03","Sangramento intermenstrual","X","Genital Feminino",1],
  ["X04","Irregularidade menstrual NE","X","Genital Feminino",1],
  ["X05","Menorragia","X","Genital Feminino",1],
  ["X06","Amenorreia/oligomenorreia","X","Genital Feminino",1],
  ["X07","Sangramento pós-menopausa","X","Genital Feminino",1],
  ["X08","Corrimento vaginal","X","Genital Feminino",1],
  ["X09","Outros sintomas genitais femininos","X","Genital Feminino",1],
  ["X10","Mamilo/queixas de mama feminina","X","Genital Feminino",1],
  ["X11","Queixas de vulva/vagina NE","X","Genital Feminino",1],
  ["X12","Queixas de puberdade NE","X","Genital Feminino",1],
  ["X13","Secreção do mamilo","X","Genital Feminino",1],
  ["X14","Queixas de menopausa","X","Genital Feminino",1],
  ["X15","Esterilidade/subfertilidade feminina","X","Genital Feminino",1],
  ["X16","Queixas de prolapso uterovaginal","X","Genital Feminino",1],
  ["X17","Outras queixas da mama NE","X","Genital Feminino",1],
  ["X18","Outros problemas relacionados ao DIU","X","Genital Feminino",1],
  ["X19","Queixas de vagina NE","X","Genital Feminino",1],
  ["X20","Medo de IST feminina","X","Genital Feminino",1],
  ["X21","Preocupação com aparência genital","X","Genital Feminino",1],
  ["X22","Medo de câncer genital feminino","X","Genital Feminino",1],
  ["X23","Medo de câncer de mama","X","Genital Feminino",1],
  ["X24","Medo de IST","X","Genital Feminino",1],
  ["X26","Medo de outras doenças genitais femininas","X","Genital Feminino",1],
  ["X27","Medo de doenças sexuais NE","X","Genital Feminino",1],
  ["X28","Limitação funcional genital feminina","X","Genital Feminino",1],
  ["X29","Outros sintomas genitais femininos NE","X","Genital Feminino",1],
  ["X70","Sífilis","X","Genital Feminino",2],
  ["X71","Gonorréia","X","Genital Feminino",2],
  ["X72","Candidíase vaginal","X","Genital Feminino",2],
  ["X73","Tricomoníase","X","Genital Feminino",2],
  ["X74","Infecção vaginal NE","X","Genital Feminino",2],
  ["X75","Cancroide","X","Genital Feminino",2],
  ["X76","Condiloma acuminado","X","Genital Feminino",2],
  ["X77","Neoplasia maligna de útero NE","X","Genital Feminino",2],
  ["X78","Neoplasia maligna do ovário","X","Genital Feminino",2],
  ["X79","Neoplasia maligna do colo uterino","X","Genital Feminino",2],
  ["X80","Neoplasia benigna genital feminina","X","Genital Feminino",2],
  ["X81","Prolapso vaginal","X","Genital Feminino",2],
  ["X82","Doenças vulvovaginais NE","X","Genital Feminino",2],
  ["X83","Inflamação pélvica","X","Genital Feminino",2],
  ["X84","Endometriose","X","Genital Feminino",2],
  ["X85","Disfunções menstruais NE","X","Genital Feminino",2],
  ["X86","Menopausa","X","Genital Feminino",2],
  ["X87","Doença inflamatória pélvica","X","Genital Feminino",2],
  ["X88","Esterilidade primária feminina","X","Genital Feminino",2],
  ["X89","Esterilidade secundária feminina","X","Genital Feminino",2],
  ["X90","Mioma uterino","X","Genital Feminino",2],
  ["X91","Cistocele/retocele","X","Genital Feminino",2],
  ["X92","Ovário policístico","X","Genital Feminino",2],
  ["X99","Outras doenças genitais femininas NE","X","Genital Feminino",2],
  // Capítulo Y — Genital Masculino
  ["Y01","Dor do pênis","Y","Genital Masculino",1],
  ["Y02","Dor do escroto/testículo","Y","Genital Masculino",1],
  ["Y03","Corrimento uretral","Y","Genital Masculino",1],
  ["Y04","Outros sintomas genitais masculinos","Y","Genital Masculino",1],
  ["Y05","Disfunção erétil/impotência sexual","Y","Genital Masculino",1],
  ["Y06","Esterilidade/subfertilidade masculina","Y","Genital Masculino",1],
  ["Y07","Queixas de prepúcio","Y","Genital Masculino",1],
  ["Y08","Queixas de próstata","Y","Genital Masculino",1],
  ["Y10","Puberdade precoce","Y","Genital Masculino",1],
  ["Y13","Queixas de escroto NE","Y","Genital Masculino",1],
  ["Y14","Outros problemas de comportamento sexual","Y","Genital Masculino",1],
  ["Y16","Queixas relacionadas à vasectomia","Y","Genital Masculino",1],
  ["Y24","Medo de câncer genital masculino","Y","Genital Masculino",1],
  ["Y25","Medo de IST masculina","Y","Genital Masculino",1],
  ["Y27","Medo de outras doenças genitais masculinas","Y","Genital Masculino",1],
  ["Y28","Limitação funcional genital masculina","Y","Genital Masculino",1],
  ["Y29","Outros sintomas genitais masculinos NE","Y","Genital Masculino",1],
  ["Y70","Sífilis masculina","Y","Genital Masculino",2],
  ["Y71","Gonorréia masculina","Y","Genital Masculino",2],
  ["Y72","Herpes genital masculino","Y","Genital Masculino",2],
  ["Y73","Condiloma masculino","Y","Genital Masculino",2],
  ["Y74","Outras IST masculinas","Y","Genital Masculino",2],
  ["Y75","Neoplasia maligna de próstata","Y","Genital Masculino",2],
  ["Y76","Neoplasia maligna testicular","Y","Genital Masculino",2],
  ["Y77","Neoplasia benigna genital masculina","Y","Genital Masculino",2],
  ["Y78","Fimose","Y","Genital Masculino",2],
  ["Y79","Traumatismo genital masculino","Y","Genital Masculino",2],
  ["Y80","Inflamação pênis/testículo","Y","Genital Masculino",2],
  ["Y81","Orquite/epididimite","Y","Genital Masculino",2],
  ["Y82","Prostatite","Y","Genital Masculino",2],
  ["Y83","Hiperplasia prostática benigna","Y","Genital Masculino",2],
  ["Y84","Hidrocele","Y","Genital Masculino",2],
  ["Y85","Varicocele","Y","Genital Masculino",2],
  ["Y86","Disfunção erétil","Y","Genital Masculino",2],
  ["Y99","Outras doenças genitais masculinas NE","Y","Genital Masculino",2],
  // Capítulo Z — Social
  ["Z01","Pobreza/problemas financeiros","Z","Social",1],
  ["Z02","Problemas alimentares/água","Z","Social",1],
  ["Z03","Problemas de moradia/vizinhança","Z","Social",1],
  ["Z04","Falta de transporte","Z","Social",1],
  ["Z05","Problemas de trabalho","Z","Social",1],
  ["Z06","Problemas de desemprego","Z","Social",1],
  ["Z07","Problemas de educação","Z","Social",1],
  ["Z08","Problemas sociais","Z","Social",1],
  ["Z09","Problemas legais","Z","Social",1],
  ["Z10","Problemas de saúde do cuidador","Z","Social",1],
  ["Z11","Problema conjugal/com parceiro","Z","Social",1],
  ["Z12","Problema com filho","Z","Social",1],
  ["Z13","Problemas com pais","Z","Social",1],
  ["Z14","Problemas familiares NE","Z","Social",1],
  ["Z15","Problemas com amigos/conhecidos","Z","Social",1],
  ["Z16","Abuso de criança NE","Z","Social",1],
  ["Z18","Problema de relacionamento NE","Z","Social",1],
  ["Z19","Perda/morte de familiar","Z","Social",1],
  ["Z20","Problema de relacionamento com cônjuge/parceiro","Z","Social",1],
  ["Z21","Problemas de comportamento de adolescente","Z","Social",1],
  ["Z22","Problema de relacionamento NE","Z","Social",1],
  ["Z23","Violência doméstica","Z","Social",1],
  ["Z24","Problemas culturais/religiosos","Z","Social",1],
  ["Z25","Problemas de vida conjugal","Z","Social",1],
  ["Z27","Medo de problemas sociais","Z","Social",1],
  ["Z28","Limitação funcional por problema social","Z","Social",1],
  ["Z29","Outros problemas sociais NE","Z","Social",1],
];

async function main() {
  const pool = new Pool({ connectionString: stripSsl(DATABASE_URL), ssl: { rejectUnauthorized: false }, max: 2 });
  const client = await pool.connect();
  try {
    const tableCheck = await client.query(
      `SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'ciap2') AS exists`
    );
    if (!tableCheck.rows[0]?.exists) {
      console.error("ERRO: tabela ciap2 não existe — execute migration 024 antes do seed");
      process.exit(1);
    }

    let inserted = 0;
    let updated = 0;
    await client.query("BEGIN");
    for (const [code, description, chapter, chapter_name, component] of CIAP2_DATA) {
      const { rowCount } = await client.query(
        `INSERT INTO ciap2 (code, description, chapter, chapter_name, component, updated_at)
         VALUES ($1, $2, $3, $4, $5, NOW())
         ON CONFLICT (code) DO UPDATE
           SET description = EXCLUDED.description,
               chapter_name = EXCLUDED.chapter_name,
               component = EXCLUDED.component,
               updated_at = NOW()
         RETURNING (xmax = 0) AS was_inserted`,
        [code, description, chapter, chapter_name, component]
      );
      if (rowCount > 0) inserted++;
      else updated++;
    }
    await client.query("COMMIT");

    const { rows } = await client.query("SELECT COUNT(*)::int AS cnt FROM ciap2");
    console.log(`seed-ciap2: inserted=${inserted} updated=${updated} total=${rows[0].cnt}`);
    if (rows[0].cnt < 650) {
      console.error(`SMOKE FAIL: esperado >= 650, obtido ${rows[0].cnt}`);
      process.exit(1);
    }
    // Smoke: código conhecido
    const { rows: known } = await client.query("SELECT description FROM ciap2 WHERE code = 'R81'");
    if (!known[0]?.description?.toLowerCase().includes("pneumonia")) {
      console.error("SMOKE FAIL: R81 não contém 'pneumonia'");
      process.exit(1);
    }
    console.log(`SMOKE PASS: ciap2 COUNT=${rows[0].cnt} >= 650; R81='${known[0].description}'`);
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {});
    console.error("ERRO:", err.message);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
  }
}

main();
