export const EMPTY_PRE_NATAL = {
  atendimento: {
    dataAtendimento: "",
    horaAtendimento: "",
    carater: "",
    linhaCuidado: "",
    localAtendimento: "ubs",
    tipoAtendimento: "",
  },
  primeiraConsulta: {
    situacaoFamiliar: "",
    trabalhaForaDeCasa: "",
    ocupacao: "",
    realizaEsforcoFisico: "",
    contatoProdutosQuimicos: "",
  },
  antecedentes: {
    familiares: [],
    pessoais: [],
    ginecologicos: {
      menarca: "",
      inicioAtividadeSexual: "",
      numeroParceiros: "",
      cicloMenstrual: "",
      regularidade: "",
      dismenorreia: "",
      metodosAnticoncepcionais: "",
    },
    obstetricos: {
      gestacoes: "",
      ectopicas: "",
      gemelares: "",
      partos: "",
      vaginais: "",
      cesareos: "",
      abortos: "",
      filhosVivos: "",
      natimortos: "",
      filhosVivosAtuais: "",
      amamentou: "",
      motivoNaoAmamentou: "",
      pretendeAmamentar: "",
    },
  },
  condicaoVacinal: {
    dtpa: "",
    hepatiteB: "",
    gripe: "",
    covid19: "",
  },
  riscos: {
    fatores: [],
  },
  acompanhamento: {
    tipoGravidez: "",
    gravidezPlanejada: "",
    dum: "",
    tipoDum: "",
    dpp: "",
    ultrassonografia: "",
    dataUltrassonografia: "",
    igSemanas: "",
    igDias: "",
  },
  exameFisico: {
    peso: "",
    altura: "",
    imc: "",
    pressaoArterial: "",
    alturaUterina: "",
    movimentacaoFetal: "",
    batimentoCardiacoFetal: "",
    observacoes: "",
  },
  exameClinico: {
    normal: "",
    observacoes: "",
  },
  exameGinecologico: {
    normal: "",
    observacoes: "",
  },
  exameMamas: {
    normal: "",
    observacoes: "",
  },
  queixas: {
    hiperemese: "",
    dorBaixoVentre: "",
    alteracoesUrinarias: "",
    sangramento: "",
    leucorreia: "",
    outrasQueixas: "",
    problemasEmocionais: "",
  },
  exames: {
    hemoglobina_glicada: "",
    vdrl: "",
    hiv: "",
    curva_glicemica: "",
    abo: "",
    rh: "",
    urina_i: "",
    urocultura: "",
    glicemia: "",
    hb: "",
    ht: "",
    hbsag: "",
    igm_toxo: "",
    usg_obstetrica: "",
    outros_exames: "",
    resultado: "",
  },
  suplementacao: {
    sulfatoFerroso: "",
    acidoFolico: "",
    outros: "",
  },
  odontologicas: {
    primeiro_trimestre: "",
    segundo_trimestre: "",
    terceiro_trimestre: "",
  },
  emulti: {
    ficouObservacao: "",
    avaliacaoDiagnostico: "",
    procedimentosTerapeuticos: "",
    prescricaoTerapeutica: "",
  },
  conduta: {
    orientacoes: [],
    encaminhamentoInterno: "",
    procedimentos: { itens: [] },
  },
};

export function buildPreNatalRecord(formData, patient) {
  const {
    atendimento = {},
    primeiraConsulta = {},
    antecedentes = {},
    acompanhamento = {},
    exameFisico = {},
    queixas = {},
    exames = {},
    conduta = {},
  } = formData;

  const detailParts = [
    acompanhamento.igSemanas ? `IG: ${acompanhamento.igSemanas}sem` : "",
    acompanhamento.dum ? `DUM: ${acompanhamento.dum}` : "",
    (conduta.orientacoes || []).length ? `Conduta: ${conduta.orientacoes.join(", ")}` : "",
  ].filter(Boolean).join(" · ");

  return {
    type: "nursing",
    title: "Pré-Natal — Consulta de Enfermagem",
    date: atendimento.dataAtendimento || new Date().toISOString().slice(0, 10),
    details: detailParts || "Consulta de pré-natal",
    metadata: {
      subtype: "pre_natal",
      workflow: "pre_natal_v1",
      localAtendimento: atendimento.localAtendimento,
      tipoAtendimento: atendimento.tipoAtendimento,
      carater: atendimento.carater,
      linhaCuidado: atendimento.linhaCuidado,
      igSemanas: acompanhamento.igSemanas,
      dum: acompanhamento.dum,
      condutaOrientacoes: conduta.orientacoes,
      procedureCodes: ((conduta.procedimentos || {}).itens || []).map(p => p.code),
      atendimento,
      primeiraConsulta,
      antecedentes,
      acompanhamento,
      exameFisico,
      queixas,
      exames,
      conduta,
      formData,
    },
  };
}
